#+TITLE: IN5050 — Video Encoding on CUDA
#+AUTHOR: Lise E. Johansen <liseej@uio.no>, Mazunki Hoksaas <rolfvh@uio.no>
#+LINK: https://www.uio.no/studier/emner/matnat/ifi/IN5050/v25/slides/in5050-exam-01.pdf

Repository for the first assignment of IN5050 by [[https://youtu.be/PfYnvDL0Qcw][Group 1]] (@liseej, @rolfvh).

* Project Layout
The code related stuff is stored inside the ~projects/~ subdirectory. Documentation is stored under the ~docs/~ subdirectory. The root level directory contains repository metadata.

  - ~docs/precode.git/~ :: Unaltered from upstream.
  - ~project/src/~ :: Contains the main code.
  - ~project/build/~ :: Compiled binaries and intermediate files.
  - ~project/include/~ :: Local header files
  - ~/usr/local/cuda~ :: Path to CUDA installation. I got mine from [[https://developer.nvidia.com/hpc-sdk-downloads][Nvidia HPC-SDK]], and symlinked the path towards ~/opt/nvidia/hpc_sdk/Linux_x86_64/2025/cuda~ after completing its default installation.
    
* Running
After dependencies are met, building and running the program should be a matter of the following:

After having run ~cmake~ succesfully for the first time, you will get ~compile_commands.json~ available in the build-dir, giving your editor's LSP sufficient information to give meaningful linting.

#+begin_src sh
  cd project

  env CC=clang CXX=clang++ NVCC_CCBIN=clang cmake -B build
  (cd build; make)

  build/c63enc
  # or
  build/c63dec
#+end_src
